# Generated by Django 5.2.7 on 2025-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mercadopago', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('datos_mercadopago', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
